CREATE INDEX "inventory_items_region_idx" ON "inventory_items" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "inventory_items_type_idx" ON "inventory_items" USING btree ("type");--> statement-breakpoint
CREATE INDEX "received_devices_tech_idx" ON "received_devices" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "received_devices_supervisor_idx" ON "received_devices" USING btree ("supervisor_id");--> statement-breakpoint
CREATE INDEX "received_devices_approved_by_idx" ON "received_devices" USING btree ("approved_by");--> statement-breakpoint
CREATE INDEX "received_devices_item_type_idx" ON "received_devices" USING btree ("item_type_id");--> statement-breakpoint
CREATE INDEX "received_devices_region_idx" ON "received_devices" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "received_devices_serial_idx" ON "received_devices" USING btree ("serial_number");--> statement-breakpoint
CREATE INDEX "stock_movements_tech_idx" ON "stock_movements" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "stock_movements_perf_idx" ON "stock_movements" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "tech_fixed_inv_tech_idx" ON "technician_fixed_inventories" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "fixed_entries_tech_idx" ON "technician_fixed_inventory_entries" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "fixed_entries_item_idx" ON "technician_fixed_inventory_entries" USING btree ("item_type_id");--> statement-breakpoint
CREATE INDEX "moving_entries_tech_idx" ON "technician_moving_inventory_entries" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "moving_entries_item_idx" ON "technician_moving_inventory_entries" USING btree ("item_type_id");--> statement-breakpoint
CREATE INDEX "tech_inv_created_by_idx" ON "technicians_inventory" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "tech_inv_region_idx" ON "technicians_inventory" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "transactions_item_id_idx" ON "transactions" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "transactions_user_id_idx" ON "transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "withdrawn_devices_created_by_idx" ON "withdrawn_devices" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "withdrawn_devices_region_idx" ON "withdrawn_devices" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "withdrawn_devices_serial_idx" ON "withdrawn_devices" USING btree ("serial_number");--> statement-breakpoint
CREATE INDEX "coa_parent_id_idx" ON "chart_of_accounts" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "einvoice_documents_source_idx" ON "einvoice_documents" USING btree ("source_type","source_id");--> statement-breakpoint
CREATE INDEX "journal_entries_created_by_idx" ON "journal_entries" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "journal_entries_posted_by_idx" ON "journal_entries" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "journal_entries_source_idx" ON "journal_entries" USING btree ("source_type","source_id");--> statement-breakpoint
CREATE INDEX "journal_entry_lines_entry_id_idx" ON "journal_entry_lines" USING btree ("entry_id");--> statement-breakpoint
CREATE INDEX "journal_entry_lines_account_id_idx" ON "journal_entry_lines" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "journal_entry_lines_region_id_idx" ON "journal_entry_lines" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "payment_allocations_payment_id_idx" ON "payment_allocations" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "payment_allocations_document_idx" ON "payment_allocations" USING btree ("document_type","document_id");--> statement-breakpoint
CREATE INDEX "payments_party_idx" ON "payments" USING btree ("party_type","party_id");--> statement-breakpoint
CREATE INDEX "payments_created_by_idx" ON "payments" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "purchase_bill_lines_bill_id_idx" ON "purchase_bill_lines" USING btree ("bill_id");--> statement-breakpoint
CREATE INDEX "purchase_bill_lines_item_type_id_idx" ON "purchase_bill_lines" USING btree ("item_type_id");--> statement-breakpoint
CREATE INDEX "purchase_bills_supplier_id_idx" ON "purchase_bills" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "purchase_bills_posted_by_idx" ON "purchase_bills" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "purchase_bills_created_by_idx" ON "purchase_bills" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "sales_invoice_lines_invoice_id_idx" ON "sales_invoice_lines" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "sales_invoice_lines_item_type_id_idx" ON "sales_invoice_lines" USING btree ("item_type_id");--> statement-breakpoint
CREATE INDEX "sales_invoice_lines_technician_id_idx" ON "sales_invoice_lines" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "sales_invoices_customer_id_idx" ON "sales_invoices" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "sales_invoices_posted_by_idx" ON "sales_invoices" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "sales_invoices_created_by_idx" ON "sales_invoices" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "sales_invoices_issue_datetime_idx" ON "sales_invoices" USING btree ("issue_datetime");--> statement-breakpoint
CREATE INDEX "tax_transactions_tax_code_id_idx" ON "tax_transactions" USING btree ("tax_code_id");--> statement-breakpoint
CREATE INDEX "tax_transactions_source_idx" ON "tax_transactions" USING btree ("source_type","source_id");--> statement-breakpoint
CREATE INDEX "tech_sales_metrics_tech_idx" ON "technician_sales_metrics_daily" USING btree ("technician_id");--> statement-breakpoint
CREATE INDEX "tech_sales_metrics_region_idx" ON "technician_sales_metrics_daily" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "tech_sales_metrics_item_idx" ON "technician_sales_metrics_daily" USING btree ("item_type_id");