import { createFixtureMatchingPorts } from "./memory-repos.js";
import type { MatchRecord } from "./types.js";

/** Seeded fixture corpus for PR-006A-6 acceptance scenarios. */
export function createMatchingFixturePorts() {
  const technicians = [
    { id: "TECH-001", name: "أحمد" },
    { id: "TECH-002", name: "سارة" },
    { id: "TECH-003", name: "خالد" },
  ];

  const executions: MatchRecord[] = [
    {
      technician_id: "TECH-001",
      technician_name: "أحمد",
      request_id: 1001,
      execution_id: "EXE-1001",
      branch: "الرياض - العليا",
      city: "الرياض",
      custody_state: "open",
      installation_status: "pending",
      serial_number: "SN-EXACT-001",
      sim_serial: "SIM-EXACT-001",
      tid: "TID-EXACT-001",
      mobile: "0500000001",
      merchant: "تاجر الدقيقة",
      incident: "INC-1001",
    },
    {
      technician_id: "TECH-002",
      technician_name: "سارة",
      request_id: 2001,
      execution_id: "EXE-2001",
      branch: "جدة - التحلية",
      city: "جدة",
      custody_state: "open",
      installation_status: "in_progress",
      serial_number: "SN-PARTIAL-002",
      sim_serial: null,
      tid: null,
      merchant: "تاجر جزئي",
      incident: "INC-2001",
    },
    {
      technician_id: "TECH-001",
      technician_name: "أحمد",
      request_id: 3001,
      execution_id: "EXE-3001A",
      branch: "الرياض - العليا",
      city: "الرياض",
      custody_state: "open",
      installation_status: "pending",
      serial_number: "SN-DUP-900",
      merchant: "تاجر مكرر",
    },
    {
      technician_id: "TECH-003",
      technician_name: "خالد",
      request_id: 3002,
      execution_id: "EXE-3001B",
      branch: "الدمام",
      city: "الدمام",
      custody_state: "open",
      installation_status: "pending",
      serial_number: "SN-DUP-900",
      merchant: "تاجر مكرر",
    },
    {
      technician_id: "TECH-002",
      technician_name: "سارة",
      request_id: 4001,
      execution_id: "EXE-4001",
      branch: "مكة",
      city: "مكة",
      custody_state: "closed",
      installation_status: "done",
      merchant: "تاجر شائع",
      serial_number: "SN-OTHER-1",
    },
    {
      technician_id: "TECH-003",
      technician_name: "خالد",
      request_id: 4002,
      execution_id: "EXE-4002",
      branch: "الطائف",
      city: "الطائف",
      custody_state: "open",
      installation_status: "pending",
      merchant: "تاجر شائع",
      serial_number: "SN-OTHER-2",
    },
    {
      technician_id: "TECH-001",
      technician_name: "أحمد",
      request_id: 5001,
      execution_id: "EXE-5001",
      branch: "المدينة",
      city: "المدينة",
      custody_state: "open",
      installation_status: "pending",
      serial_number: "SN-NO-TID",
      sim_serial: null,
      tid: null,
    },
  ];

  return createFixtureMatchingPorts({
    technicians,
    requests: [
      { request_id: 1001, incident: "INC-1001" },
      { request_id: 2001, incident: "INC-2001" },
      { request_id: 3001 },
      { request_id: 3002 },
      { request_id: 4001 },
      { request_id: 4002 },
      { request_id: 5001 },
    ],
    executions,
    merchants: [
      { name: "تاجر الدقيقة", branch: "الرياض - العليا", city: "الرياض" },
      { name: "تاجر جزئي", branch: "جدة - التحلية", city: "جدة" },
      { name: "تاجر مكرر", city: "الرياض" },
      { name: "تاجر شائع" },
    ],
    branches: [
      { name: "الرياض - العليا", city: "الرياض" },
      { name: "جدة - التحلية", city: "جدة" },
      { name: "المدينة", city: "المدينة" },
    ],
  });
}
